### ISSUE TITLE
Set up documentation generation

### ISSUE THREAD

**Issue by annwhoorma** [IU-MAP/avzag#37]
https://www.npmjs.com/package/jsdoc

**Comment by annwhoorma** [comment]
there is branch issue-37 regarding jsdoc
i added config file for jsdoc and installed the package

i ran:
./node_modules/.bin/jsdoc src -r -d docs -c jsdoc.config.json

meaning of the flags:
-r - recursive
-d docs - destination
-c jsdoc.config.json - config file 

the problem is that it returned a lot of messages like "Unexpected token" and "Missing semicolon"

besides that, there is "This experimental syntax requires enabling one of the following parser plugin(s): 'flow, typescript'" - i tried googling but couldnt figure out how to add the plugins

**Comment by annwhoorma** [comment]
![image](https://user-images.githubusercontent.com/34862867/114231705-735a5f00-9983-11eb-9aee-1ba6e1b42a7b.png)
this is jsdoc.config.json - configuration file for jsdoc

it's just like the default one but i also included ts, d.ts, .vue to `includePattern`

the message i talked about above says that i need to enable 2 plugins but i dont have any plugins to put to plugins (second line of the file)

**Comment by annwhoorma** [comment]
read [this](https://jsdoc.app/plugins-markdown.html) but didnt help

**Comment by annwhoorma** [comment]
[fix for typescript plugin](https://www.npmjs.com/package/jsdoc-plugin-typescript)

**Comment by annwhoorma** [comment]
tried [this](https://www.npmjs.com/package/vuepress-jsdoc)

idk why but i couldnt set up jsdoc to parse all the files even though I enabled all the necessary plugins (from my point of view)

i added jsdoc-flow and jsdoc-plugin-typescript

**Comment by annwhoorma** [comment]
what we'll most probably use: [vuese](https://github.com/vuese/vuese)

**Comment by alkaitagi** [comment]
Will be looking at this: https://tsdoc.org/.

**Comment by annwhoorma** [comment]
the final version: **using typedoc**
run this:
`yarn typedoc --out docs src/*.ts`
