### ISSUE TITLE
As a user, I want to have an offline access to the dictionary, so that I can use it in situations with no access to internet

### ISSUE THREAD

**Issue by annwhoorma** [IU-MAP/avzag#8]

**Comment by QazyBi** [comment]
Why not to make the project a mobile application?

**Comment by QazyBi** [comment]
@alkaitagi Do you have any strong argument for having such requirement?

**Comment by annwhoorma** [comment]
@QazyBi has it been resolved? I think we discussed it during the last meeting but I'll put it here:
**the main reason is that potential users might have bad or no connection**, however, I agree that this requirement might force @alkaitagi to write a mobile application at some point :)

**Comment by alkaitagi** [comment]
> @QazyBi has it been resolved? I think we discussed it during the last meeting but I'll put it here:
> **the main reason is that potential users might have bad or no connection**, however, I agree that this requirement might force @alkaitagi to write a mobile application at some point :)

A good idea of diploma.
